import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Box } from '@mui/system';
import { Typography } from '@mui/material';
import NavBar from '@/components/NavBar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Box maxWidth={'100vw'} minHeight={'100vh'} bgcolor={'lightblue'} className='relative'>
          <NavBar />
          {children}
          <Box className='w-full flex justify-center absolute bottom-0'>
            <Typography variant='caption'>©️Support by Phantec clouding computing</Typography>
          </Box>
        </Box>
      </body>
    </html>
  );
}
